apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-limit-pod
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-limit
  template:
    metadata:
      labels:
        app: nginx-limit
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-limit
  namespace: nginx-limit-pod
spec:
  type: NodePort
  selector:
    app: nginx-limit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081